// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace GNRGameplayTags
{
	/** Input Tags **/
	GNR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	GNR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	GNR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	GNR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Dash);
	GNR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Shoot);
	GNR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Skill);
	GNR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Unequip);

	/** Player Tags **/
	GNR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Jump);
	GNR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Dash);
	GNR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Shoot);
	GNR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Skill);
	GNR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip);

	GNR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Cooldown_Dash);
	GNR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Cooldown_Shoot);
	GNR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Cooldown_Skill);

	/** Enemy Tags **/
	GNR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon);
	GNR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Attack);
	GNR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Charge);

	/** Shared Tags **/
	GNR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact);
	GNR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Death);

	GNR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact);
	GNR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit);

	GNR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Death);

	GNR_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_AttackPower);
}
